Repository MUTUAL-DE-SERVICIOS-AL-POLICIA/Beneficiary-Interface, pull requests merged in 2024-11, with the labels that each got.

#27 Moviendo la lógica de obtención de datos para las huelas biometricas, implementación de cerrado de sesión, agregando alertas
  app/api/logout/route.ts
  app/beneficiaries/page.tsx
  app/beneficiaries/service.ts
  app/beneficiary/[id]/(profile)/(person-data)/fingerprints/page.tsx
  app/beneficiary/[id]/(profile)/(person-data)/page.tsx
  app/beneficiary/[id]/(profile)/(person-data)/servicePersonData.tsx
  app/beneficiary/[id]/(profile)/affiliate-data/(sections)/DerelictInfo.tsx
  app/beneficiary/[id]/(profile)/affiliate-data/(sections)/Documents.tsx
  app/beneficiary/[id]/(profile)/affiliate-data/(sections)/EntryInfo.tsx
  app/beneficiary/[id]/(profile)/affiliate-data/(sections)/ServiceInfo.tsx
  app/beneficiary/[id]/(profile)/affiliate-data/(sections)/StateInfo.tsx
  app/beneficiary/[id]/(profile)/affiliate-data/page.tsx
  app/beneficiary/[id]/(profile)/layout.tsx
  app/beneficiary/[id]/layout.tsx
  app/beneficiary/service.ts
  app/layout.tsx
  app/not-found.tsx
  components/navbar.tsx
  components/sidebar.tsx
  components/table.tsx
  components/user.tsx
  context/AlertProvider.tsx
  context/BeneficiaryContext.tsx
  hooks/useAlerts.tsx
  middleware.ts
  package.json
  services/APIConnection.ts
  services/FetchServiceFactory.ts
  yarn.lock
Labels: enhancement, refactorization

#29 Arreglando el envío de cookie, en las peticiones API's
  app/beneficiaries/service.ts
  components/table.tsx
  helpers/cookie.ts
  services/APIConnection.ts
Labels: bug

#30 Quitando opciones del menu del sidebar y corrigiendo bugs
  app/beneficiary/[id]/(profile)/(person-data)/(sections)/AddressInfo.tsx
  app/beneficiary/[id]/(profile)/(person-data)/(sections)/DeathInfo.tsx
  app/beneficiary/[id]/(profile)/(person-data)/(sections)/FinancialData.tsx
  app/beneficiary/[id]/(profile)/(person-data)/fingerprints/page.tsx
  app/beneficiary/[id]/(profile)/(person-data)/page.tsx
  app/beneficiary/[id]/(profile)/affiliate-data/(sections)/DerelictInfo.tsx
  app/beneficiary/[id]/(profile)/affiliate-data/(sections)/Documents.tsx
  app/beneficiary/[id]/(profile)/affiliate-data/(sections)/EntryInfo.tsx
  app/beneficiary/[id]/(profile)/affiliate-data/(sections)/ServiceInfo.tsx
  app/beneficiary/[id]/(profile)/affiliate-data/(sections)/StateInfo.tsx
  app/beneficiary/[id]/(profile)/beneficiaries/page.tsx
  app/beneficiary/[id]/(profile)/relations/page.tsx
  components/accordion.tsx
  components/sidebar.tsx
  components/user.tsx
  config/static.tsx
  services/FetchService.ts
Labels: enhancement

#31 Cambio en el nombre de la cookie
  app/api/logout/route.ts
  helpers/cookie.ts
  middleware.ts
  services/APIConnection.ts
Labels: refactorization
