Repository MUTUAL-DE-SERVICIOS-AL-POLICIA/Beneficiary-Interface, pull requests merged in 2025-06, with the labels that each got.

#72 Development a testin actualización
  src/app/layout.tsx
  src/components/persons/sidebarMenu/affiliates/affiliates.tsx
  src/components/persons/sidebarMenu/beneficiaries/beneficiaries.tsx
  src/components/persons/sidebarMenu/person/information/modalFingerprints.tsx
  src/components/persons/sidebarMenu/sidebar.tsx
Labels: enhancement

#74 redirección al login despues de logout
  src/components/header/user.tsx
Labels: enhancement

#75 Development a testing
  src/components/header/user.tsx
Labels: enhancement

#77 Development a testing
  src/components/header/user.tsx
  src/middleware.ts
Labels: bug

#78 Testing A Main redirección
  src/components/header/user.tsx
  src/middleware.ts
Labels: bug, enhancement

#80 COMPONENTES REUTILIZABLES PARA INPUTS DE FECHA, COPIADO DE CI Y DRAWER DE TELÉFONOS
  package.json
  pnpm-lock.yaml
  src/components/common/copyButton.tsx
  src/components/common/dateInput.tsx
  src/components/common/icons.tsx
  src/components/common/index.ts
  src/components/common/input.tsx
  src/components/header/user.tsx
  src/components/persons/sidebarMenu/person/information/basic.tsx
  src/components/persons/sidebarMenu/person/information/death.tsx
  src/components/persons/sidebarMenu/person/information/phones.tsx
  src/components/persons/sidebarMenu/police/information/derelict.tsx
  src/components/persons/sidebarMenu/police/information/entry.tsx
  src/components/persons/sidebarMenu/sidebar.tsx
  src/components/persons/sidebarMenu/userInfo.tsx
Labels: enhancement

#81 IMPLEMENTACIÓN SIDEBAR MENU, RESPONSIVIDAD POR TAMAÑO DE PANTALLA
  src/app/layout.tsx
  src/app/persons/[uuid]/layout.tsx
  src/app/persons/layout.tsx
  src/app/persons/page.tsx
  src/app/providers.tsx
  src/components/common/icons.tsx
  src/components/common/index.ts
  src/components/common/primitives.ts
  src/components/header/navbar.tsx
  src/components/header/sidebarRoot.tsx
  src/components/persons/sidebarMenu/affiliates/affiliates.tsx
  src/components/persons/sidebarMenu/beneficiaries/beneficiaries.tsx
  src/components/persons/sidebarMenu/index.ts
  src/components/persons/sidebarMenu/person/personalData.tsx
  src/components/persons/sidebarMenu/police/information/document.tsx
  src/components/persons/sidebarMenu/sidebar.tsx
  src/components/persons/sidebarMenu/userInfo.tsx
  src/components/persons/table.tsx
  src/utils/interfaces/index.ts
  src/utils/types/index.ts
Labels: enhancement
